import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedloginscreenwidget1/generated/GeneratedJatureport_app2Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedloginscreenwidget1/generated/GeneratedGroup55Widget.dart';

/* Frame LOGIN SCREEN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLOGINSCREENWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 168.0,
                top: 671.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 71.0,
                child: GeneratedGroup55Widget(),
              ),
              Positioned(
                left: 64.0,
                top: 288.0,
                right: null,
                bottom: null,
                width: 286.0,
                height: 266.0,
                child: GeneratedJatureport_app2Widget(),
              )
            ]),
      ),
    ));
  }
}
