import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedopinionviewpagewidget/generated/GeneratedGroup18Widget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedopinionviewpagewidget/generated/GeneratedLeftarrow7Widget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedopinionviewpagewidget/generated/GeneratedLeftarrow6Widget2.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedopinionviewpagewidget/generated/GeneratedViewWidget7.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedopinionviewpagewidget/generated/GeneratedGroup11Widget15.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedopinionviewpagewidget/generated/GeneratedViewWidget10.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedopinionviewpagewidget/generated/GeneratedViewWidget9.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedopinionviewpagewidget/generated/GeneratedViewWidget8.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedopinionviewpagewidget/generated/GeneratedLeftarrow8Widget1.dart';

/* Frame OPINION VIEW PAGE
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOPINIONVIEWPAGEWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1273.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 64.0,
                              right: null,
                              bottom: null,
                              width: 26.0,
                              height: 20.0,
                              child: GeneratedLeftarrow6Widget2(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 64.0,
                              right: null,
                              bottom: null,
                              width: 26.0,
                              height: 20.0,
                              child: GeneratedLeftarrow8Widget1(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 64.0,
                              right: null,
                              bottom: null,
                              width: 26.0,
                              height: 20.0,
                              child: GeneratedLeftarrow7Widget1(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 380.0,
                              right: null,
                              bottom: null,
                              width: 58.0,
                              height: 33.0,
                              child: GeneratedViewWidget7(),
                            ),
                            Positioned(
                              left: 104.0,
                              top: 900.0,
                              right: null,
                              bottom: null,
                              width: 58.0,
                              height: 33.0,
                              child: GeneratedViewWidget8(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 720.0,
                              right: null,
                              bottom: null,
                              width: 58.0,
                              height: 33.0,
                              child: GeneratedViewWidget9(),
                            ),
                            Positioned(
                              left: 104.0,
                              top: 1240.0,
                              right: null,
                              bottom: null,
                              width: 58.0,
                              height: 33.0,
                              child: GeneratedViewWidget10(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 68.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 119.0,
                              child: GeneratedGroup18Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -6.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 74.0,
                              child: GeneratedGroup11Widget15(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
