import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlisttargetspagewidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlisttargetspagewidget/generated/GeneratedEyecloseup5Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlisttargetspagewidget/generated/GeneratedEyecloseup3Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlisttargetspagewidget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlisttargetspagewidget/generated/GeneratedEyecloseup2Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlisttargetspagewidget/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlisttargetspagewidget/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlisttargetspagewidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlisttargetspagewidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlisttargetspagewidget/generated/GeneratedEyecloseup4Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlisttargetspagewidget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlisttargetspagewidget/generated/GeneratedGroup11Widget11.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlisttargetspagewidget/generated/GeneratedGroup3Widget.dart';

/* Frame LIST TARGETS PAGE
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLISTTARGETSPAGEWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1182.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 1182.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 90.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 119.0,
                              child: GeneratedGroup3Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 492.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 119.0,
                              child: GeneratedGroup6Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 224.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 119.0,
                              child: GeneratedGroup4Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 626.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 119.0,
                              child: GeneratedGroup7Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 894.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 119.0,
                              child: GeneratedGroup9Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 358.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 119.0,
                              child: GeneratedGroup5Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 760.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 119.0,
                              child: GeneratedGroup8Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1028.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 119.0,
                              child: GeneratedGroup10Widget(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 360.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 16.0,
                              child: GeneratedEyecloseup2Widget(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 526.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 16.0,
                              child: GeneratedEyecloseup3Widget(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 693.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 16.0,
                              child: GeneratedEyecloseup4Widget(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 16.0,
                              child: GeneratedEyecloseup5Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 74.0,
                              child: GeneratedGroup11Widget11(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
