import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcommentedreportwidget/generated/GeneratedGroup41Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcommentedreportwidget/generated/GeneratedGroup45Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcommentedreportwidget/generated/GeneratedGroup44Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcommentedreportwidget/generated/GeneratedGroup11Widget17.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcommentedreportwidget/generated/GeneratedGroup43Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcommentedreportwidget/generated/GeneratedGroup42Widget.dart';

/* Frame COMMENTED REPORT
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCOMMENTEDREPORTWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 1.0,
                top: 71.0,
                right: null,
                bottom: null,
                width: 405.0,
                height: 146.0,
                child: GeneratedGroup41Widget(),
              ),
              Positioned(
                left: 3.0,
                top: 233.0,
                right: null,
                bottom: null,
                width: 405.0,
                height: 146.0,
                child: GeneratedGroup42Widget(),
              ),
              Positioned(
                left: 8.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 405.0,
                height: 146.0,
                child: GeneratedGroup43Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 557.0,
                right: null,
                bottom: null,
                width: 405.0,
                height: 146.0,
                child: GeneratedGroup44Widget(),
              ),
              Positioned(
                left: 5.0,
                top: 719.0,
                right: null,
                bottom: null,
                width: 405.0,
                height: 146.0,
                child: GeneratedGroup45Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 74.0,
                child: GeneratedGroup11Widget17(),
              )
            ]),
      ),
    ));
  }
}
