import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetask2screenwidget/generated/GeneratedRectangle141Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetask2screenwidget/generated/GeneratedTasktitleWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetask2screenwidget/generated/GeneratedReportTimeWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetask2screenwidget/generated/GeneratedGroup11Widget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetask2screenwidget/generated/GeneratedTaskResultsWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetask2screenwidget/generated/GeneratedRectangle143Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetask2screenwidget/generated/GeneratedTaskChallengesWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetask2screenwidget/generated/GeneratedTaskDescriptionWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetask2screenwidget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetask2screenwidget/generated/GeneratedRectangle144Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetask2screenwidget/generated/GeneratedRectangle139Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetask2screenwidget/generated/GeneratedTimeTakenWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetask2screenwidget/generated/GeneratedADDTASKWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetask2screenwidget/generated/GeneratedRectangle140Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetask2screenwidget/generated/GeneratedTotalTasks0Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetask2screenwidget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetask2screenwidget/generated/GeneratedRectangle142Widget.dart';

/* Frame CREATE TASK2 SCREEN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCREATETASK2SCREENWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 252, 255, 253),
                ),
              ),
              Positioned(
                left: 12.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 23.0,
                child: GeneratedTasktitleWidget(),
              ),
              Positioned(
                left: 12.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 23.0,
                child: GeneratedTimeTakenWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 23.0,
                child: GeneratedTaskDescriptionWidget(),
              ),
              Positioned(
                left: 157.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 23.0,
                child: GeneratedReportTimeWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 23.0,
                child: GeneratedTaskResultsWidget(),
              ),
              Positioned(
                left: 12.0,
                top: 593.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 23.0,
                child: GeneratedTaskChallengesWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 766.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 45.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 47.0,
                top: 778.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 23.0,
                child: GeneratedADDTASKWidget(),
              ),
              Positioned(
                left: 238.0,
                top: 116.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 45.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 256.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 23.0,
                child: GeneratedTotalTasks0Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 379.0,
                height: 60.0,
                child: GeneratedRectangle139Widget(),
              ),
              Positioned(
                left: 151.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 37.0,
                child: GeneratedRectangle143Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 37.0,
                child: GeneratedRectangle144Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 379.0,
                height: 60.0,
                child: GeneratedRectangle140Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 379.0,
                height: 98.0,
                child: GeneratedRectangle141Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 636.0,
                right: null,
                bottom: null,
                width: 379.0,
                height: 111.0,
                child: GeneratedRectangle142Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 74.0,
                child: GeneratedGroup11Widget1(),
              )
            ]),
      ),
    ));
  }
}
