import 'package:flutter/material.dart';

/* Frame SPLASH SCREEN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSPLASHSCREENWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedLOGINSCREENWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 414.0,
          height: 896.0,
          child: ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 219, 110, 38),
            ),
          ),
        ),
      ),
    ));
  }
}
