import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetargetpagewidget/generated/GeneratedTargettitleWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetargetpagewidget/generated/GeneratedGroup11Widget7.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetargetpagewidget/generated/GeneratedLeftarrow11Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetargetpagewidget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreatetargetpagewidget/generated/GeneratedGroup24Widget.dart';

/* Frame CREATE TARGET PAGE
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCREATETARGETPAGEWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 22.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 20.0,
                child: GeneratedLeftarrow11Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 23.0,
                child: GeneratedTargettitleWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 151.0,
                right: null,
                bottom: null,
                width: 367.0,
                height: 2.0,
                child: GeneratedLine6Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 194.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 45.0,
                child: GeneratedGroup24Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 2.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 74.0,
                child: GeneratedGroup11Widget7(),
              )
            ]),
      ),
    ));
  }
}
