import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedtargetscreenwidget/generated/GeneratedGroup29Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedtargetscreenwidget/generated/GeneratedLeftarrow13Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedtargetscreenwidget/generated/GeneratedGroup26Widget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedtargetscreenwidget/generated/GeneratedLeftarrow12Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedtargetscreenwidget/generated/GeneratedGroup11Widget3.dart';

/* Frame TARGET SCREEN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTARGETSCREENWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 23.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 20.0,
                child: GeneratedLeftarrow12Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 20.0,
                child: GeneratedLeftarrow13Widget(),
              ),
              Positioned(
                left: 6.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 255.0,
                child: GeneratedGroup29Widget(),
              ),
              Positioned(
                left: 1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 74.0,
                child: GeneratedGroup11Widget3(),
              ),
              Positioned(
                left: 6.0,
                top: 78.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 217.0,
                child: GeneratedGroup26Widget1(),
              )
            ]),
      ),
    ));
  }
}
