import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpasswordsettingpagewidget/generated/GeneratedOLDPASSWORDWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpasswordsettingpagewidget/generated/GeneratedLine6Widget2.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpasswordsettingpagewidget/generated/GeneratedLeftarrow6Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpasswordsettingpagewidget/generated/GeneratedUpdateWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpasswordsettingpagewidget/generated/GeneratedLine8Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpasswordsettingpagewidget/generated/GeneratedNEWPASSWORDWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpasswordsettingpagewidget/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpasswordsettingpagewidget/generated/GeneratedCONFIRMPASSWORDWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpasswordsettingpagewidget/generated/GeneratedRectangle14Widget3.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpasswordsettingpagewidget/generated/GeneratedGroup11Widget9.dart';

/* Frame PASSWORD SETTING PAGE
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPASSWORDSETTINGPAGEWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 22.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 20.0,
                child: GeneratedLeftarrow6Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 23.0,
                child: GeneratedOLDPASSWORDWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 214.0,
                right: null,
                bottom: null,
                width: 367.0,
                height: 2.0,
                child: GeneratedLine6Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 23.0,
                child: GeneratedNEWPASSWORDWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 367.0,
                height: 2.0,
                child: GeneratedLine7Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 23.0,
                child: GeneratedCONFIRMPASSWORDWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 367.0,
                height: 2.0,
                child: GeneratedLine8Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 45.0,
                child: GeneratedRectangle14Widget3(),
              ),
              Positioned(
                left: 66.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 26.0,
                child: GeneratedUpdateWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 74.0,
                child: GeneratedGroup11Widget9(),
              )
            ]),
      ),
    ));
  }
}
