import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/GeneratedJatureportingsystemdesignWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/GeneratedTargetWidget2.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/GeneratedAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/GeneratedReport1Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/GeneratedGroup22Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/GeneratedTimetakenWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/GeneratedAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/GeneratedTaskResultsWidget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/GeneratedRectangle133Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/GeneratedRectangle138Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/GeneratedTasksWidget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/GeneratedTaskChallengesWidget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/GeneratedGroup11Widget2.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/GeneratedRectangle136Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/GeneratedRectangle137Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/Generated4HrsWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/GeneratedRectangle135Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/GeneratedTodesignuserandHODpanelWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/GeneratedTanzaniaisanEastAfricancountryknownforitsvastwildernepo.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/GeneratedTaskDescriptionWidget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/GeneratedRectangle134Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreportscreenwidget/generated/GeneratedGroup23Widget.dart';

/* Frame REPORT SCREEN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedREPORTSCREENWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1022.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 1022.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 252, 255, 253),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 758.0,
                              right: null,
                              bottom: null,
                              width: 133.0,
                              height: 23.0,
                              child: GeneratedTaskChallengesWidget1(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 218.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 28.0,
                              child: GeneratedTargetWidget2(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 287.0,
                              right: null,
                              bottom: null,
                              width: 58.0,
                              height: 28.0,
                              child: GeneratedTasksWidget1(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 351.0,
                              right: null,
                              bottom: null,
                              width: 101.0,
                              height: 25.0,
                              child: GeneratedTimetakenWidget(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 413.0,
                              right: null,
                              bottom: null,
                              width: 164.0,
                              height: 25.0,
                              child: GeneratedTaskDescriptionWidget1(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 585.0,
                              right: null,
                              bottom: null,
                              width: 124.0,
                              height: 25.0,
                              child: GeneratedTaskResultsWidget1(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 963.0,
                              right: null,
                              bottom: null,
                              width: 169.0,
                              height: 34.0,
                              child: GeneratedGroup22Widget(),
                            ),
                            Positioned(
                              left: 210.0,
                              top: 963.0,
                              right: null,
                              bottom: null,
                              width: 169.0,
                              height: 34.0,
                              child: GeneratedGroup23Widget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 99.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 114.0,
                              child: GeneratedReport1Widget(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 247.0,
                              right: null,
                              bottom: null,
                              width: 368.0,
                              height: 28.0,
                              child: GeneratedRectangle133Widget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 313.0,
                              right: null,
                              bottom: null,
                              width: 368.0,
                              height: 28.0,
                              child: GeneratedRectangle134Widget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 374.0,
                              right: null,
                              bottom: null,
                              width: 368.0,
                              height: 28.0,
                              child: GeneratedRectangle135Widget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 440.0,
                              right: null,
                              bottom: null,
                              width: 368.0,
                              height: 134.0,
                              child: GeneratedRectangle136Widget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 617.0,
                              right: null,
                              bottom: null,
                              width: 368.0,
                              height: 134.0,
                              child: GeneratedRectangle137Widget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 791.0,
                              right: null,
                              bottom: null,
                              width: 368.0,
                              height: 134.0,
                              child: GeneratedRectangle138Widget(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 251.0,
                              right: null,
                              bottom: null,
                              width: 258.0,
                              height: 25.0,
                              child: GeneratedJatureportingsystemdesignWidget(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 315.0,
                              right: null,
                              bottom: null,
                              width: 267.0,
                              height: 25.0,
                              child: GeneratedTodesignuserandHODpanelWidget(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 377.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 28.0,
                              child: Generated4HrsWidget(),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 447.0,
                              right: null,
                              bottom: null,
                              width: 356.0,
                              height: 99.0,
                              child:
                                  GeneratedTanzaniaisanEastAfricancountryknownforitsvastwildernepo(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 632.0,
                              right: null,
                              bottom: null,
                              width: 350.0,
                              height: 120.0,
                              child:
                                  GeneratedAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 802.0,
                              right: null,
                              bottom: null,
                              width: 358.0,
                              height: 120.0,
                              child:
                                  GeneratedAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 74.0,
                              child: GeneratedGroup11Widget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
