import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedprofilempyascreenwidget/generated/GeneratedGroup52Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedprofilempyascreenwidget/generated/GeneratedLine9Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedprofilempyascreenwidget/generated/GeneratedGroup51Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedprofilempyascreenwidget/generated/GeneratedGroup53Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedprofilempyascreenwidget/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedprofilempyascreenwidget/generated/GeneratedGroup54Widget.dart';

/* Frame PROFILE MPYA SCREEN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPROFILEMPYASCREENWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1091.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 1091.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 242, 242, 242),
                              ),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 293.0,
                              right: null,
                              bottom: null,
                              width: 319.0,
                              height: 1.0,
                              child: GeneratedLine9Widget(),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 116.0,
                              right: null,
                              bottom: null,
                              width: 365.0,
                              height: 263.0,
                              child: GeneratedGroup53Widget(),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 404.0,
                              right: null,
                              bottom: null,
                              width: 365.0,
                              height: 276.0,
                              child: GeneratedGroup51Widget(),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 705.0,
                              right: null,
                              bottom: null,
                              width: 365.0,
                              height: 276.0,
                              child: GeneratedGroup52Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -2.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 74.0,
                              child: GeneratedGroup11Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1032.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 59.0,
                              child: GeneratedGroup54Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
