import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistopinionpagewidget/generated/GeneratedGroup12Widget6.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistopinionpagewidget/generated/GeneratedGroup11Widget14.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistopinionpagewidget/generated/GeneratedViewWidget6.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistopinionpagewidget/generated/GeneratedGroup13Widget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistopinionpagewidget/generated/GeneratedLeftarrow8Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistopinionpagewidget/generated/GeneratedViewTargetsWidget14.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistopinionpagewidget/generated/GeneratedGroup16Widget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistopinionpagewidget/generated/GeneratedGroup15Widget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistopinionpagewidget/generated/GeneratedGroup14Widget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistopinionpagewidget/generated/GeneratedGroup17Widget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistopinionpagewidget/generated/GeneratedDoublecheck2Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistopinionpagewidget/generated/GeneratedLeftarrow6Widget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistopinionpagewidget/generated/GeneratedLeftarrow7Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistopinionpagewidget/generated/GeneratedViewWidget5.dart';

/* Frame LIST OPINION PAGE
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLISTOPINIONPAGEWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1273.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 997.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 64.0,
                              right: null,
                              bottom: null,
                              width: 26.0,
                              height: 20.0,
                              child: GeneratedLeftarrow6Widget1(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 64.0,
                              right: null,
                              bottom: null,
                              width: 26.0,
                              height: 20.0,
                              child: GeneratedLeftarrow8Widget(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 64.0,
                              right: null,
                              bottom: null,
                              width: 26.0,
                              height: 20.0,
                              child: GeneratedLeftarrow7Widget(),
                            ),
                            Positioned(
                              left: 148.0,
                              top: 22.0,
                              right: null,
                              bottom: null,
                              width: 129.0,
                              height: 30.0,
                              child: GeneratedViewTargetsWidget14(),
                            ),
                            Positioned(
                              left: 104.0,
                              top: 900.0,
                              right: null,
                              bottom: null,
                              width: 58.0,
                              height: 33.0,
                              child: GeneratedViewWidget5(),
                            ),
                            Positioned(
                              left: 104.0,
                              top: 1240.0,
                              right: null,
                              bottom: null,
                              width: 58.0,
                              height: 33.0,
                              child: GeneratedViewWidget6(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 104.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 119.0,
                              child: GeneratedGroup12Widget6(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 248.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 119.0,
                              child: GeneratedGroup13Widget1(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 392.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 119.0,
                              child: GeneratedGroup14Widget1(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 532.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 119.0,
                              child: GeneratedGroup15Widget1(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 674.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 119.0,
                              child: GeneratedGroup16Widget1(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 828.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 119.0,
                              child: GeneratedGroup17Widget1(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 482.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 25.0,
                              child: GeneratedDoublecheck2Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 74.0,
                              child: GeneratedGroup11Widget14(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
