import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistreportpagewidget1/generated/GeneratedGroup15Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistreportpagewidget1/generated/GeneratedGroup11Widget13.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistreportpagewidget1/generated/GeneratedGroup17Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistreportpagewidget1/generated/GeneratedGroup16Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistreportpagewidget1/generated/GeneratedGroup13Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistreportpagewidget1/generated/GeneratedGroup3Widget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistreportpagewidget1/generated/GeneratedEdit5Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistreportpagewidget1/generated/GeneratedGroup12Widget5.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistreportpagewidget1/generated/GeneratedGroup14Widget.dart';

/* Frame LIST REPORT PAGE
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLISTREPORTPAGEWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 940.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 940.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 95.0,
                              top: 864.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 15.0,
                              child: GeneratedEdit5Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 90.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 116.0,
                              child: GeneratedGroup3Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 332.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 116.0,
                              child: GeneratedGroup13Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 695.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 116.0,
                              child: GeneratedGroup15Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 211.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 116.0,
                              child: GeneratedGroup12Widget5(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 574.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 116.0,
                              child: GeneratedGroup16Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 453.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 116.0,
                              child: GeneratedGroup14Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 816.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 116.0,
                              child: GeneratedGroup17Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -2.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 74.0,
                              child: GeneratedGroup11Widget13(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
