import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpermissionpagewidget/generated/GeneratedAppDeveloperWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpermissionpagewidget/generated/GeneratedICTWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpermissionpagewidget/generated/GeneratedToDateWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpermissionpagewidget/generated/GeneratedShedrackKitomariWidget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpermissionpagewidget/generated/GeneratedNameWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpermissionpagewidget/generated/Generated20201109Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpermissionpagewidget/generated/GeneratedFromDateWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpermissionpagewidget/generated/GeneratedIrequestWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpermissionpagewidget/generated/GeneratedRequestWidget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpermissionpagewidget/generated/GeneratedDepartmentWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpermissionpagewidget/generated/GeneratedPositionWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpermissionpagewidget/generated/GeneratedGroup11Widget8.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpermissionpagewidget/generated/Generated20201109Widget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpermissionpagewidget/generated/GeneratedLine6Widget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpermissionpagewidget/generated/GeneratedRectangle14Widget2.dart';

/* Frame PERMISSION PAGE
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPERMISSIONPAGEWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 147.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 30.0,
                child: GeneratedNameWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 30.0,
                child: GeneratedFromDateWidget(),
              ),
              Positioned(
                left: 53.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 30.0,
                child: GeneratedToDateWidget(),
              ),
              Positioned(
                left: 124.0,
                top: 147.0,
                right: null,
                bottom: null,
                width: 202.0,
                height: 30.0,
                child: GeneratedShedrackKitomariWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 30.0,
                child: GeneratedPositionWidget(),
              ),
              Positioned(
                left: 124.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 30.0,
                child: GeneratedAppDeveloperWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 237.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 30.0,
                child: GeneratedDepartmentWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 30.0,
                child: GeneratedIrequestWidget(),
              ),
              Positioned(
                left: 160.0,
                top: 237.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 30.0,
                child: GeneratedICTWidget(),
              ),
              Positioned(
                left: 168.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 33.0,
                child: Generated20201109Widget(),
              ),
              Positioned(
                left: 168.0,
                top: 573.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 33.0,
                child: Generated20201109Widget1(),
              ),
              Positioned(
                left: 23.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 367.0,
                height: 2.0,
                child: GeneratedLine6Widget1(),
              ),
              Positioned(
                left: 23.0,
                top: 649.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 45.0,
                child: GeneratedRectangle14Widget2(),
              ),
              Positioned(
                left: 63.0,
                top: 661.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 26.0,
                child: GeneratedRequestWidget1(),
              ),
              Positioned(
                left: 3.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 74.0,
                child: GeneratedGroup11Widget8(),
              )
            ]),
      ),
    ));
  }
}
