import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedhomescreenwidget/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedhomescreenwidget/generated/GeneratedHomeWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedhomescreenwidget/generated/GeneratedOpinionsWidget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedhomescreenwidget/generated/GeneratedMenu1Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedhomescreenwidget/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedhomescreenwidget/generated/GeneratedQuickTipsWidget.dart';

/* Frame HOME SCREEN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHOMESCREENWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 252, 253, 253),
                ),
              ),
              Positioned(
                left: 30.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 30.0,
                child: GeneratedQuickTipsWidget(),
              ),
              Positioned(
                left: 11.0,
                top: 322.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 339.0,
                child: GeneratedGroup19Widget(),
              ),
              Positioned(
                left: 252.0,
                top: 660.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 33.0,
                child: GeneratedOpinionsWidget1(),
              ),
              Positioned(
                left: 23.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedMenu1Widget(),
              ),
              Positioned(
                left: 174.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 33.0,
                child: GeneratedHomeWidget(),
              ),
              Positioned(
                left: 7.0,
                top: 81.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 217.0,
                child: GeneratedGroup18Widget(),
              )
            ]),
      ),
    ));
  }
}
