import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreporttabsscreenwidget/generated/GeneratedDocument2Widget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreporttabsscreenwidget/generated/GeneratedCommentedbackreportWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreporttabsscreenwidget/generated/GeneratedRectangle11Widget3.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreporttabsscreenwidget/generated/GeneratedRectangle11Widget4.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreporttabsscreenwidget/generated/GeneratedExplainexplainexplainexplainexplainexplainexplainexplai1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreporttabsscreenwidget/generated/GeneratedRectangle11Widget5.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreporttabsscreenwidget/generated/GeneratedAllreportsWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreporttabsscreenwidget/generated/GeneratedReportWidget3.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreporttabsscreenwidget/generated/GeneratedDocument3Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreporttabsscreenwidget/generated/GeneratedSentreportWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreporttabsscreenwidget/generated/Generated1Yourrequiredtocreatetargetforeachweeksothateachtaskcan1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreporttabsscreenwidget/generated/GeneratedRectangle13Widget3.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreporttabsscreenwidget/generated/GeneratedDocument1Widget2.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreporttabsscreenwidget/generated/Generated2Youcanviewyourtargetanytimeyouwantsothatyoucanreviewth.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreporttabsscreenwidget/generated/GeneratedGroup11Widget4.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedreporttabsscreenwidget/generated/GeneratedRectangle12Widget1.dart';

/* Frame REPORT TABS SCREEN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedREPORTTABSSCREENWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 6.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 243.0,
                child: GeneratedRectangle11Widget3(),
              ),
              Positioned(
                left: 22.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 30.0,
                child: GeneratedReportWidget3(),
              ),
              Positioned(
                left: 13.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 34.0,
                child:
                    Generated2Youcanviewyourtargetanytimeyouwantsothatyoucanreviewth(),
              ),
              Positioned(
                left: 12.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 34.0,
                child:
                    Generated1Yourrequiredtocreatetargetforeachweeksothateachtaskcan1(),
              ),
              Positioned(
                left: 8.0,
                top: 366.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 421.0,
                child: GeneratedRectangle11Widget4(),
              ),
              Positioned(
                left: 27.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 134.0,
                child: GeneratedRectangle11Widget5(),
              ),
              Positioned(
                left: 32.0,
                top: 632.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 134.0,
                child: GeneratedRectangle13Widget3(),
              ),
              Positioned(
                left: 69.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 86.0,
                child: GeneratedDocument1Widget2(),
              ),
              Positioned(
                left: 156.0,
                top: 646.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 86.0,
                child: GeneratedDocument3Widget(),
              ),
              Positioned(
                left: 47.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 30.0,
                child: GeneratedSentreportWidget(),
              ),
              Positioned(
                left: 69.0,
                top: 735.0,
                right: null,
                bottom: null,
                width: 289.0,
                height: 30.0,
                child: GeneratedCommentedbackreportWidget(),
              ),
              Positioned(
                left: 214.0,
                top: 474.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 134.0,
                child: GeneratedRectangle12Widget1(),
              ),
              Positioned(
                left: 256.0,
                top: 474.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 86.0,
                child: GeneratedDocument2Widget1(),
              ),
              Positioned(
                left: 238.0,
                top: 569.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 30.0,
                child: GeneratedAllreportsWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 50.0,
                child:
                    GeneratedExplainexplainexplainexplainexplainexplainexplainexplai1(),
              ),
              Positioned(
                left: 1.0,
                top: -2.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 74.0,
                child: GeneratedGroup11Widget4(),
              )
            ]),
      ),
    ));
  }
}
