import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreateopinionpagewidget/generated/GeneratedSaveWidget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreateopinionpagewidget/generated/GeneratedEnterOpinionWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreateopinionpagewidget/generated/GeneratedRectangle14Widget4.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreateopinionpagewidget/generated/GeneratedGroup11Widget10.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedcreateopinionpagewidget/generated/GeneratedRectangle145Widget.dart';

/* Frame CREATE OPINION PAGE
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCREATEOPINIONPAGEWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 85.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 23.0,
                child: GeneratedEnterOpinionWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 386.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 45.0,
                child: GeneratedRectangle14Widget4(),
              ),
              Positioned(
                left: 74.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 26.0,
                child: GeneratedSaveWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 74.0,
                child: GeneratedGroup11Widget10(),
              ),
              Positioned(
                left: 21.0,
                top: 132.0,
                right: null,
                bottom: null,
                width: 369.0,
                height: 228.0,
                child: GeneratedRectangle145Widget(),
              )
            ]),
      ),
    ));
  }
}
