import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedallreportpagewidget/generated/GeneratedGroup49Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedallreportpagewidget/generated/GeneratedGroup46Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedallreportpagewidget/generated/GeneratedGroup47Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedallreportpagewidget/generated/GeneratedGroup48Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedallreportpagewidget/generated/GeneratedGroup11Widget16.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedallreportpagewidget/generated/GeneratedGroup50Widget.dart';

/* Frame ALL REPORT PAGE
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedALLREPORTPAGEWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 1.0,
                top: 74.0,
                right: null,
                bottom: null,
                width: 405.0,
                height: 146.0,
                child: GeneratedGroup46Widget(),
              ),
              Positioned(
                left: 3.0,
                top: 236.0,
                right: null,
                bottom: null,
                width: 405.0,
                height: 146.0,
                child: GeneratedGroup47Widget(),
              ),
              Positioned(
                left: 8.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 405.0,
                height: 146.0,
                child: GeneratedGroup48Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 405.0,
                height: 146.0,
                child: GeneratedGroup49Widget(),
              ),
              Positioned(
                left: 5.0,
                top: 722.0,
                right: null,
                bottom: null,
                width: 405.0,
                height: 146.0,
                child: GeneratedGroup50Widget(),
              ),
              Positioned(
                left: 1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 74.0,
                child: GeneratedGroup11Widget16(),
              )
            ]),
      ),
    ));
  }
}
