import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedloginscreenwidget/generated/GeneratedLOGINWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedloginscreenwidget/generated/GeneratedForgetyourpasswordClickhereWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedloginscreenwidget/generated/GeneratedJatureport_app1Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedloginscreenwidget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedloginscreenwidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedloginscreenwidget/generated/GeneratedPadlock1Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedloginscreenwidget/generated/GeneratedRectangle1Widget.dart';

/* Frame LOGIN SCREEN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLOGINSCREENWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 219, 110, 38),
              Color.fromARGB(255, 235, 87, 87)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 26.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 180.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 26.0,
                child: GeneratedLOGINWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 76.99547576904297,
                top: 494.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedPadlock1Widget(),
              ),
              Positioned(
                left: 103.0,
                top: 625.0,
                right: null,
                bottom: null,
                width: 210.0,
                height: 18.0,
                child: GeneratedForgetyourpasswordClickhereWidget(),
              ),
              Positioned(
                left: 62.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 286.0,
                height: 266.0,
                child: GeneratedJatureport_app1Widget(),
              )
            ]),
      ),
    ));
  }
}
