import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistreportpagewidget/generated/GeneratedGroup36Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistreportpagewidget/generated/GeneratedGroup40Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistreportpagewidget/generated/GeneratedGroup11Widget12.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistreportpagewidget/generated/GeneratedGroup39Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistreportpagewidget/generated/GeneratedGroup37Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedlistreportpagewidget/generated/GeneratedGroup38Widget.dart';

/* Frame LIST REPORT PAGE
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLISTREPORTPAGEWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 896.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 2.0,
                              top: 82.0,
                              right: null,
                              bottom: null,
                              width: 405.0,
                              height: 146.0,
                              child: GeneratedGroup36Widget(),
                            ),
                            Positioned(
                              left: 4.0,
                              top: 244.0,
                              right: null,
                              bottom: null,
                              width: 405.0,
                              height: 146.0,
                              child: GeneratedGroup37Widget(),
                            ),
                            Positioned(
                              left: 9.0,
                              top: 406.0,
                              right: null,
                              bottom: null,
                              width: 405.0,
                              height: 146.0,
                              child: GeneratedGroup38Widget(),
                            ),
                            Positioned(
                              left: 11.0,
                              top: 568.0,
                              right: null,
                              bottom: null,
                              width: 405.0,
                              height: 146.0,
                              child: GeneratedGroup39Widget(),
                            ),
                            Positioned(
                              left: 6.0,
                              top: 730.0,
                              right: null,
                              bottom: null,
                              width: 405.0,
                              height: 146.0,
                              child: GeneratedGroup40Widget(),
                            ),
                            Positioned(
                              left: -3.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 74.0,
                              child: GeneratedGroup11Widget12(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
