import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpermissionrequestpagewidget/generated/GeneratedLeftarrow13Widget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpermissionrequestpagewidget/generated/GeneratedGroup25Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpermissionrequestpagewidget/generated/GeneratedGroup11Widget6.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpermissionrequestpagewidget/generated/Generated1Yourrequiredtocreatetargetforeachweeksothateachtaskcan4.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedpermissionrequestpagewidget/generated/GeneratedGroup20Widget2.dart';

/* Frame PERMISSION REQUEST PAGE
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPERMISSIONREQUESTPAGEWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 21.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 20.0,
                child: GeneratedLeftarrow13Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 34.0,
                child:
                    Generated1Yourrequiredtocreatetargetforeachweeksothateachtaskcan4(),
              ),
              Positioned(
                left: 10.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 261.0,
                child: GeneratedGroup25Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 74.0,
                child: GeneratedGroup11Widget6(),
              ),
              Positioned(
                left: 6.0,
                top: 84.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 217.0,
                child: GeneratedGroup20Widget2(),
              )
            ]),
      ),
    ));
  }
}
