import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedopiniontabsscreenwidget/generated/GeneratedGroup11Widget5.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedopiniontabsscreenwidget/generated/Generated1Yourrequiredtocreatetargetforeachweeksothateachtaskcan2.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedopiniontabsscreenwidget/generated/Generated2Youcanviewyourtargetanytimeyouwantsothatyoucanreviewth1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedopiniontabsscreenwidget/generated/GeneratedGroup21Widget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedopiniontabsscreenwidget/generated/GeneratedGroup20Widget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedopiniontabsscreenwidget/generated/Generated1Yourrequiredtocreatetargetforeachweeksothateachtaskcan3.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedopiniontabsscreenwidget/generated/GeneratedOpinionsSuggestionsWidget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedopiniontabsscreenwidget/generated/GeneratedLeftarrow18Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatedopiniontabsscreenwidget/generated/GeneratedReportWidget4.dart';

/* Frame OPINION TABS SCREEN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOPINIONTABSSCREENWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 25.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 30.0,
                child: GeneratedReportWidget4(),
              ),
              Positioned(
                left: 16.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 381.0,
                height: 34.0,
                child:
                    Generated2Youcanviewyourtargetanytimeyouwantsothatyoucanreviewth1(),
              ),
              Positioned(
                left: 15.0,
                top: 166.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 34.0,
                child:
                    Generated1Yourrequiredtocreatetargetforeachweeksothateachtaskcan2(),
              ),
              Positioned(
                left: 16.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 34.0,
                child:
                    Generated1Yourrequiredtocreatetargetforeachweeksothateachtaskcan3(),
              ),
              Positioned(
                left: 7.0,
                top: 339.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 261.0,
                child: GeneratedGroup21Widget1(),
              ),
              Positioned(
                left: 97.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 242.0,
                height: 33.0,
                child: GeneratedOpinionsSuggestionsWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 20.0,
                child: GeneratedLeftarrow18Widget(),
              ),
              Positioned(
                left: 8.0,
                top: 102.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 217.0,
                child: GeneratedGroup20Widget1(),
              ),
              Positioned(
                left: -1.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 74.0,
                child: GeneratedGroup11Widget5(),
              )
            ]),
      ),
    ));
  }
}
