import 'package:flutter/material.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatednavigationscreenwidget/generated/Generated1IfyoustuckdonthesitatetoaccesstheHELPlinkontheleftbott1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatednavigationscreenwidget/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatednavigationscreenwidget/generated/GeneratedHomeWidget1.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatednavigationscreenwidget/generated/GeneratedGroup28Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatednavigationscreenwidget/generated/Generated2Youcanusethetabsappearsinthetablestonavigatethroughdif.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatednavigationscreenwidget/generated/GeneratedGroup21Widget.dart';
import 'package:flutterapp/jatu_20report_20systemapp/generatednavigationscreenwidget/generated/GeneratedMenu2Widget.dart';

/* Frame NAVIGATION SCREEN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNAVIGATIONSCREENWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 252, 255, 253),
                ),
              ),
              Positioned(
                left: -115.0,
                top: 151.0,
                right: null,
                bottom: null,
                width: 500.0,
                height: 66.0,
                child:
                    Generated1IfyoustuckdonthesitatetoaccesstheHELPlinkontheleftbott1(),
              ),
              Positioned(
                left: 17.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 371.0,
                height: 34.0,
                child:
                    Generated2Youcanusethetabsappearsinthetablestonavigatethroughdif(),
              ),
              Positioned(
                left: 10.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 339.0,
                child: GeneratedGroup20Widget(),
              ),
              Positioned(
                left: 6.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 217.0,
                child: GeneratedGroup21Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedMenu2Widget(),
              ),
              Positioned(
                left: 176.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 33.0,
                child: GeneratedHomeWidget1(),
              ),
              Positioned(
                left: 1.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 301.0,
                height: 896.0,
                child: GeneratedGroup28Widget(),
              )
            ]),
      ),
    ));
  }
}
